# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  TargetRailsVersion: 7.1
  Exclude:
    - "bin/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"
    - "db/schema.rb"

# Layout
Layout/LineLength:
  Max: 120
  Exclude:
    - "config/**/*"

Layout/MultilineArrayBraceLayout:
  EnforcedStyle: new_line

# Naming
Naming/FileName:
  Enabled: false

# Rails
Rails/CreateTableWithTimestamps:
  Enabled: true

# RSpec
RSpec/DescribedClass:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

# Metrics
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "db/migrate/*"

Metrics/MethodLength:
  Max: 15
  Exclude:
    - "db/migrate/*"
